// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCiliumVRFs implements CiliumVRFInterface
type FakeCiliumVRFs struct {
	Fake *FakeCiliumV2alpha1
}

var ciliumvrfsResource = schema.GroupVersionResource{Group: "cilium.io", Version: "v2alpha1", Resource: "ciliumvrfs"}

var ciliumvrfsKind = schema.GroupVersionKind{Group: "cilium.io", Version: "v2alpha1", Kind: "CiliumVRF"}

// Get takes name of the ciliumVRF, and returns the corresponding ciliumVRF object, and an error if there is any.
func (c *FakeCiliumVRFs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumVRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(ciliumvrfsResource, name), &v2alpha1.CiliumVRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumVRF), err
}

// List takes label and field selectors, and returns the list of CiliumVRFs that match those selectors.
func (c *FakeCiliumVRFs) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumVRFList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(ciliumvrfsResource, ciliumvrfsKind, opts), &v2alpha1.CiliumVRFList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.CiliumVRFList{ListMeta: obj.(*v2alpha1.CiliumVRFList).ListMeta}
	for _, item := range obj.(*v2alpha1.CiliumVRFList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ciliumVRFs.
func (c *FakeCiliumVRFs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(ciliumvrfsResource, opts))
}

// Create takes the representation of a ciliumVRF and creates it.  Returns the server's representation of the ciliumVRF, and an error, if there is any.
func (c *FakeCiliumVRFs) Create(ctx context.Context, ciliumVRF *v2alpha1.CiliumVRF, opts v1.CreateOptions) (result *v2alpha1.CiliumVRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(ciliumvrfsResource, ciliumVRF), &v2alpha1.CiliumVRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumVRF), err
}

// Update takes the representation of a ciliumVRF and updates it. Returns the server's representation of the ciliumVRF, and an error, if there is any.
func (c *FakeCiliumVRFs) Update(ctx context.Context, ciliumVRF *v2alpha1.CiliumVRF, opts v1.UpdateOptions) (result *v2alpha1.CiliumVRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(ciliumvrfsResource, ciliumVRF), &v2alpha1.CiliumVRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumVRF), err
}

// Delete takes name of the ciliumVRF and deletes it. Returns an error if one occurs.
func (c *FakeCiliumVRFs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(ciliumvrfsResource, name, opts), &v2alpha1.CiliumVRF{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCiliumVRFs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(ciliumvrfsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.CiliumVRFList{})
	return err
}

// Patch applies the patch and returns the patched ciliumVRF.
func (c *FakeCiliumVRFs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumVRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(ciliumvrfsResource, name, pt, data, subresources...), &v2alpha1.CiliumVRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumVRF), err
}
