// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumVRFLister helps list CiliumVRFs.
// All objects returned here must be treated as read-only.
type CiliumVRFLister interface {
	// List lists all CiliumVRFs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumVRF, err error)
	// Get retrieves the CiliumVRF from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumVRF, error)
	CiliumVRFListerExpansion
}

// ciliumVRFLister implements the CiliumVRFLister interface.
type ciliumVRFLister struct {
	indexer cache.Indexer
}

// NewCiliumVRFLister returns a new CiliumVRFLister.
func NewCiliumVRFLister(indexer cache.Indexer) CiliumVRFLister {
	return &ciliumVRFLister{indexer: indexer}
}

// List lists all CiliumVRFs in the indexer.
func (s *ciliumVRFLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumVRF, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumVRF))
	})
	return ret, err
}

// Get retrieves the CiliumVRF from the index for a given name.
func (s *ciliumVRFLister) Get(name string) (*v2alpha1.CiliumVRF, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumvrf"), name)
	}
	return obj.(*v2alpha1.CiliumVRF), nil
}
